services:
  masm611:
    image: aathish04/masm611:latest
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./programs:/home/dosbox/programs
    stdin_open: true 
    tty: true